<?php

namespace OneThirtyWordsBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRecent()
    {
        return $this->createQueryBuilder('p')
            ->join('p.user', 'u')
            ->groupBy('p.date', 'u')
            ->orderBy('p.date', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
