<?php

namespace OneThirtyWordsBundle\Repository;

use OneThirtyWordsBundle\Entity\User;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRecent()
    {
        return $this->createQueryBuilder('p')
            ->join('p.user', 'u')
            ->groupBy('p.date', 'u')
            ->orderBy('p.date', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function getPostsByUser(User $user)
    {
        return $this->createQueryBuilder('p')
            ->join('p.user', 'u')
            ->where('u.id = :user_id')
            ->groupBy('p.date', 'u')
            ->orderBy('p.date', 'DESC')
            ->setParameter('user_id', $user->getId())
            ->getQuery()
            ->getResult();
    }
}
